### PR TITLE
Version 0.10

### PR DESCRIPTION
**Pull request by FGRibreau**
`docker run -it --rm fgribreau/influxdb:0.10.0`

https://hub.docker.com/r/fgribreau/influxdb/tags/

### CODE REVIEW

**Comment by tifayuki** [comment]
Thank you

**Comment by janantala** [comment]
There is still legacy configuration from 0.9.x release! https://www.diffchecker.com/04xu5cuo

**Comment by FGRibreau** [comment]
@janantala don't hesitate to send a PR for it :)

**Comment by flangelier** [comment]
Some feature from the run.sh (like #79) haven't been "merge" with this PR
It will be great to have the latest run.sh in 0.10

**Pull request merged**
