### PR TITLE
Upgrade to 0.9.3

### PR DESCRIPTION
**Pull request by skozin**
New version of InfluxDB [has been released](https://influxdb.com/blog/2015/08/26/InfluxDB-0_9_3-released-with-compression-and-improved-write-throughput.html). It offers improved write throughput, data compression and couple of [breaking](https://github.com/influxdb/influxdb/issues/3519) [changes](https://github.com/influxdb/influxdb/pull/3599).

### CODE REVIEW

**Comment by tifayuki** [comment]
Thank you

**Comment by skozin** [comment]
You're welcome :)

**Comment by eliperelman** [comment]
@skozin do you know when this will be pushed to docker?

**Comment by tifayuki** [comment]
@skozin It looks like the docker hub auto build doesn't work correctly. I have triggered a build manually. It will be available soon in a few minutes.

**Comment by eliperelman** [comment]
@tifayuki @skozin any chance the build can be tagged separately from `0.9`, like `0.9.3`?

**Pull request merged**
