### PR TITLE
Fix: start daemon directly in foreground for signal handling

### PR DESCRIPTION
**Pull request by william-p**
Hello,
with this fix ```docker stop``` work properly.

Have a nice day

### CODE REVIEW

**Comment by tifayuki** [comment]
Do you mean if a process is not started in foreground directly, it will not receive the signals?

**Comment by william-p** [comment]
Yes, in this case (normal ?) `fg` command don't forward SIGTERM signal to InfluxDB.

You can experiment like this:

    # In one shell
    docker run -it --rm --name influxdb tutum/influxdb:0.9

    # In second shell (simulate normal 'docker stop'), nothing happen
    docker kill -s SIGTERM influxdb

    # If you send signal directly to the process, Influxdb stop properly (see first shell output)
    docker exec -it influxdb bash -c 'kill -s SIGTERM $(pidof influxd)'

Another experiment with `docker stop`:
    
    $ time docker stop influxdb
    influxdb
    real	0m10.305s

According to the [documentation](https://docs.docker.com/engine/reference/commandline/stop/) Influxdb was stopped by SIGKILL ...

My fix was inspired by MySQL entrypoint: https://github.com/docker-library/mysql/blob/master/5.5/docker-entrypoint.sh#L113

What do you think ? can you reproduce ?

**Comment by william-p** [comment]
Maybe a Docker issue, i don't known ...

```
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:54:53 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:54:53 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by tifayuki** [comment]
True. The same result here.
Can you rebase the PR, so that I can merge it?

**Comment by william-p** [comment]
Yes, big changes in `run.sh` ... I do it.

**Comment by william-p** [comment]
It's ok on my side, if someone can test it :)
Maybe same issue in 0.10 ...

**Comment by tifayuki** [comment]
Thank you

**Pull request merged**
