### PR TITLE
Fixes to make 0.9.2 working

### PR DESCRIPTION
**Pull request by aheusingfeld**
- updated config.toml for Graphite plugin
- updated config.toml for UDP
- added creation of 'admin' user to run.sh (TODO: review needed)
- commented out seemingly obsolete parts in run.sh (TODO: review needed)

This should tackle #22.

### CODE REVIEW

**Comment by tifayuki** [comment]
Hi @aheusingfeld 

Instead of forcing creating the `admin` user, I think it is better to use an environment variable like `CREATE_DB_USER=admin:admin_pass`.

The rest looks good to me.

**Comment by aheusingfeld** [comment]
@tifayuki I added another patch adapting your changes and tweaked a little more after some extensive testing

**Comment by tifayuki** [comment]
Thank you

**Comment by aheusingfeld** [comment]
You're welcome. You might want to review the config.toml though, I'm not absolutely sure the values represent common sense.

Keep up the great work! ;)

**Pull request merged**
